S2 us5/page details
WildCodeSchool-2024-02/js-toulouse-p2-moovies_lib pull request #9
Opened 2024-04-18 17:51 UTC by Modrum04

Code of component person and code of Details page are over.
Not started scss.
Who want to correct me ? (please use your most powerfull weapon)

2024-04-18 19:47 UTC, RomainRG31 requested changes
Super ! C'est beau à lire 😁 Pour ma part, j'approuve. Rien de ce que tu as mis ne me " choque " ou ne nécessiterait un changement mis à part peut-être **sass** dans les **dependencies** et remplacer "r" dans ta callback par "res ou response" ? 😜 J'aime beaucoup ton switch/case pour la popularité. Juste une remarque :  je ne comprends pas à quoi sert ces lignes de code : "i === arr.length - 1 ? genre.name : `${genre.name}, `" ?

2024-04-18 21:34 UTC, Modrum04 commented
Pour  "i === arr.length - 1 ? genre.name : ${genre.name}, " cela veit simplement dire que lorsque le tableau comporte plusieurs elements, alors il faut mettre une virgule entre eux dans le texte, sauf pour le dernier.
Par contre je comprends pas ce que tu veux que je changes par rapport à ton label "change requested" ?

2024-04-20 08:17 UTC, Modrum04 commented
J'ai terminé la page Détails et tous les éléments visuels la concernant.
Merci à celui qui me fait sa review.
Bon weekend

2024-04-20 19:38 UTC, RomainRG31 approved these changes
Tristan, bravo. Je valide ta PR de mon côté. J'ai quelques questions concernant le scss que je te ferai de vive voix Lundi. Bon week-end Mr Beast.

2024-04-22 08:04 UTC, ArthurHtbk approved these changes

2024-04-22 08:04 UTC, merged